### ISSUE TITLE
Connection ID Duplicated in status message

### ISSUE THREAD

**Issue by KingOfBrian** [opentok/presencekit-php#18]
I'm curious why you're using the format of "<connectionId>~status" as the message type. It doesn't seem needed since it's the same as the connectionId, and it puts data into the message type, which seems to be bad practice as well.

I'm implementing a swift version that connects with presence kit and thought I'd ask.

Brian

**Comment by aoberoi** [comment]
@KingOfBrian thanks for the comment. the idea behind using the signal type `"<connectionId>~status"` was extensibility and modularity. we could have just used `"status"` and receivers could either infer the connection ID whose status was being communicated using the `from` property of the signal, or by explicitly encoding the connection ID in the data of the signal.

the reason why i consider the current type more modular is because each RemoteUser instance can directly listen for signals of type related to the connection ID it actually cares about. otherwise, if you just used "status" you might need the dispatcher to receive and then route all those signals to the correct RemoteUser instance, which would then update, and broadcast yet another change over the dispatcher. its also more extensible because in the future you could send more than just a status for each RemoteUser. for example lets say you added an avatar URL for each user, and update could be signal type `"<connectionId>~avatarUrl"`. The RemoteUser instance would just subscribe to one more signal type. 

i hope that makes sense, but if you have a reason why you think renaming those signal types would have an advantage, i'm interested to hear and would consider changing it.

btw, if you're willing to share, it would be fantastic to see how your swift client is coming along!

**Comment by KingOfBrian** [comment]
I can see that the extensibility can be nice. Even so it's a bit strange to have some messages conform to this and not others. Usually I'd just force the client to add that logic  by adding the `connectionId` themselves. So for the backbone implementation dispatch the `messageType`, and then dispatch `messageType~connectionId` and let the consumer subscribe to one or the other.... Warning: I'm not a javascript person and this was the first time reading javascript in a few years so I may of butchered all of the terms there.

I was actually coming back here to explain that this may of been a required implementation as well. When the client first connects with another client connected it receives a `receivedSignalType` delegate message with a nil client, so without the `clientId` elsewhere in the payload things would be broken. Not sure if this was part of the motivation or an SDK bug on the javascript side as well. 

I'm not sure I'll be able to publish this app, I'm hoping I can. We will be changing our implementation substantially when we exit the prototype stage, but I wanted an iOS app to interoperate with this demo that we could extend to some degree.

Any thoughts on a swift update to the SDK? Nullability changes and updating adding a BOOL return to the `:(OTError **)error` methods would be great.

**Comment by aoberoi** [comment]
>  Usually I'd just force the client to add that logic by adding the connectionId themselves. So for the backbone implementation dispatch the messageType, and then dispatch messageType~connectionId and let the consumer subscribe to one or the other.

i could see the utility in having "topics" and "sub-topics", but thats not a natural part of the current OpenTok signaling functionality. i think forcing the sending client to send both, even though both do not get used is any other part of the application would have been unnecessary at this point in time, but i think its a reasonable feature to add. in that case, implementation wise, i would make a client-side object that wrapped OpenTok signaling and (de)multiplexes a single application event to multiple "topic" and "subtopic" signals. IMHO that would be cleaner.

> When the client first connects with another client connected it receives a receivedSignalType delegate message with a nil client, so without the clientId elsewhere in the payload things would be broken.

that is actually a known bug in the platform, and will be fixed in an upcoming release. It only affects the mobile SDKs (iOS and Android). the suggested workaround for now would be to not depend on the "connectionCreated" event (or delegate message) to trigger sending a signal to the newly connecting client, but to make the new client announce itself via a signal (sometime after the "sessionConnected" event or delegate message), and then the previously connected clients would send the signal.

no pressure in sharing any implementation you have! we might be willing to work with you on it and publish or blog about your code if you did have something to share.

as for a swift update to the SDK, i agree with you. i wrote a Swift-y HelloWorld alternative myself: https://github.com/aoberoi/OpenTok-HelloWorld-iOS. the automatic translation of the APIs seems to be to be reasonable enough to get work done, but the error handling and nullability are definitely areas for improvement. i'll take that feedback to the team, but as of now, there's no explicit plans to make our iOS SDK Swift-first yet.

**Comment by KingOfBrian** [comment]
Hey, so thanks for the input here,  helped me understand the design. We've published our PresenceKit demo here - https://github.com/Raizlabs/OpenTokPresence

It's still pretty rough around the edges UI wise, but should get a few more updates before we move on.

Thanks!
